# Generated by Django 6.0.4 on 2026-05-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colaboradores", "emprestimo_data_sem_hora"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emprestimo",
            name="data_devolucao",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="emprestimo",
            name="data_entrega",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="emprestimo",
            name="data_prevista_devolucao",
            field=models.DateTimeField(),
        ),
    ]
