# Generated by Django 6.0.4 on 2026-05-09 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colaboradores", "cadastro_colaborador"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=140)),
                ("codigo", models.CharField(blank=True, max_length=60)),
                ("quantidade", models.PositiveIntegerField(default=1)),
                ("descricao", models.TextField(blank=True)),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Emprestimo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField(default=1)),
                ("data_entrega", models.DateTimeField()),
                ("data_prevista_devolucao", models.DateTimeField()),
                ("data_devolucao", models.DateTimeField(blank=True, null=True)),
                ("observacao_devolucao", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("emprestado", "Emprestado"),
                            ("fornecido", "Fornecido"),
                            ("devolvido", "Devolvido"),
                            ("danificado", "Danificado"),
                            ("perdido", "Perdido"),
                        ],
                        default="emprestado",
                        max_length=20,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emprestimos",
                        to="colaboradores.colaborador",
                    ),
                ),
                (
                    "equipamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emprestimos",
                        to="colaboradores.equipamento",
                    ),
                ),
            ],
            options={
                "ordering": ["-criado_em"],
            },
        ),
    ]
